### ISSUE TITLE
demo 启动报错，redis是正常启动

### ISSUE THREAD

**Issue by iamzxj** [fayechenlong/plumelog#7]
com.plumelog.core.exception.LogQueueConnectException: redis 写入失败！
	at com.plumelog.core.redis.RedisClient.putMessageList(RedisClient.java:135)
	at com.plumelog.core.MessageAppenderFactory.push(MessageAppenderFactory.java:63)
	at com.plumelog.core.MessageAppenderFactory.startTraceLog(MessageAppenderFactory.java:110)
	at com.plumelog.logback.appender.RedisAppender.lambda$start$1(RedisAppender.java:119)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisExhaustedPoolException: Could not get a resource since the pool is exhausted
	at redis.clients.jedis.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
	at com.plumelog.core.redis.RedisClient.putMessageList(RedisClient.java:128)
	... 6 more
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:491)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 8 more

**Comment by fayechenlong** [comment]
请移步码云下载最新版本 https://gitee.com/frankchenlong/plumelog github因为网络问题更新慢
